input-output-hk/lace-ui-toolkit

- src/design-system/text/text.css.ts
- src/design-system/text/text.stories.tsx
- src/icons/WarningIconCircleComponent.tsx
- src/icons/index.ts
- src/icons/raw/warning-icon-circle.component.svg
Sync Lace change from this PR: https://github.com/input-output-hk/lace/pull/1116
> feat: add warning text variation

- .github/actions/chromatic/action.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- package.json
> ci: setup chromatic

- .github/workflows/publish.yml
In order to publish chromatic we need to fetch full git history in publish.yml workflow (the same as we do in ci.yml)
> ci: fetch full git history to publish chromatic

- CONTRIBUTING.md
- README.md
- package.json
> docs: add CONTRIBUTING guide

- .github/workflows/publish.yml
Allow semantic release to push changed files to main branch, and remove leftovers from using `GITHUB_TOKEN`
> ci: allow semantic-release to push changed files

- src/design-system/file-upload/file-upload.component.tsx
- src/design-system/file-upload/file-upload.css.ts
- src/design-system/file-upload/file-upload.stories.tsx
- src/design-tokens/typography.data.ts
- onRemove triggering file upload on click.
- Label format needs to be more flexible on the extension (related to LW-10531).
> fix: on remove triggering file upload click and label changes

- src/design-system/text-link/text-link.component.tsx
- src/design-system/text-link/text-link.css.ts
- src/design-system/text-link/text-link.stories.tsx
This PR adds a new variant to the `TextLink` component which previously was designed with a hardcoded horizontal padding on both sides, which only makes sense if it is used within surrounding text but not when used standalone (e.g a single link on one line).
This highlights the problem before this PR:
With the new prop `standalone=true` it can be used also as standalone variant without padding:
> feat: add limited px prop to text link component [LW-10645]

- src/design-system/info-bar/info-bar.component.tsx
Make InfoBar component accepts ReactNode instead of string
> feat: change message property type for info bar component

- src/design-system/text/text.css.ts
- src/design-tokens/colors.data.ts
- src/design-tokens/sx.css.ts
- src/design-tokens/theme/dark-theme.css.ts
- src/design-tokens/theme/light-theme.css.ts
- src/icons/LockIconGradientComponent.tsx
- src/icons/PlusIconGradientComponent.tsx
- src/icons/index.ts
- src/icons/raw/lock-icon-gradient.component.svg
- src/icons/raw/plus-icon-gradient.component.svg
This PR introduces new wallet onboarding options icons. Also, one new text colors is introduced: `laceGradient`.
Screenshots:
> feat: add wallet onboarding icons and additional colors [LW-10641]

- src/design-system/password-box/password-box-button.css.ts
This PR fixes an issue with the `<PasswordBox>` component required for https://input-output.atlassian.net/browse/LW-10644 where the "show/hide password" button icon is not correctly centered when used there:
I have no idea how it could have been correctly aligned before (in Storybook it looks correct) since there are no styles for centering it, so it seems it was probably coincidence that it worked so far.
This is how it looks after this fix:
> fix: center eye icon in password input component [LW-10644]

- src/design-system/password-box/password-box-button.component.tsx
- src/design-system/password-box/password-box-input.component.tsx
This PR introduces the missing `testId` implementation for PasswordBox and its toggle button (preview).
> test: add test ids for PasswordBox [LW-10799]

- src/design-system/index.ts
- src/design-system/password-box/index.ts
- src/design-system/password-box/uncontrolled-password-box-input.component.tsx
- src/design-system/password-box/uncontrolled-password-box.component.tsx
a variant of PasswordBox that doesn't have 'value' property
also, 'onChange' callback provides both the password and the input el
This component should eventually replace the original PasswordBox. At that point we'll update the stories.
> feat: add UncontrolledPasswordBox

- src/design-system/password-box/uncontrolled-password-box-input.component.tsx
A unit test in `lace` was failing after replacing Password with this component. Tested it with this change.
> fix: pass autoFocus prop to uncontrolled pw input element

- src/design-system/profile-dropdown/index.ts
- src/design-system/profile-dropdown/profile-dropdown-trigger.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-trigger.stories.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-card.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-option.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-status.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-status.css.ts
- src/design-system/profile-dropdown/profile-dropdown.stories.tsx
This PR introduces profile dropdown component adjustments so we can use them in a more scalable way and perform different variations.
**Examples:** 
**_1. Profile Dropdown Trigger component_**
**Story:** https://6422dc516f0543c5fd174d4c-vlcriuqujt.chromatic.com/?path=/story/navigation-and-toolbars-profile-dropdown-trigger--overview
**_2. Profile Dropdown Wallet Status component_**
**Story:** https://6422dc516f0543c5fd174d4c-vlcriuqujt.chromatic.com/?path=/story/navigation-and-toolbars-profile-dropdown--overview
> chore: make profile dropdown more scalable

- src/design-system/assets-table/assets-table-token-amount.component.tsx
- src/design-system/assets-table/assets-table-token-profile.component.tsx
- src/design-system/profile-picture/image.component.tsx
ad missing id for tokens list section
> feat: add test ids for tokens table list lw-10959

- src/design-system/profile-dropdown/profile-dropdown-trigger.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-trigger.stories.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-card.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-option.component.tsx
This PR introduces a more robust way of loading images or even custom components ( with / without image ) to the profile dropdown root component and options component.
In this way we don't have to use base64 images to load them and it simplifies XSY code
**Screenshots:**
> feat: allow custom components as profile dropdown profile image

- src/design-system/box/box.component.tsx
Box component doesnt render `data-testid` on its inner div. This PR adds a new property `testId` to the Box component.
> fix: box component now has a new property testId what will be rendered in the data-testid prop

- src/design-system/asset-input/amount-input.component.tsx
- src/design-system/asset-input/index.ts
- src/design-system/asset-input/simple-asset-input.component.tsx
- src/design-system/bundle-input/bundle-input.component.tsx
- src/design-system/index.ts
This PR adds additional improvements for the `AmountInput` and `SimpleAssetInput`:
- allow to pass a specific `test-dataid` prop to `AmountInput` while not changing the old way of using the `id` prop (that might be how it's done in Lace)
- allow to pass a `test-dataid` to `SimpleAssetInput` and pass it on to `AmountInput` required by the e2e send-flow tests
- export the asset input data types as discussed here https://github.com/input-output-hk/xsy-wallet/pull/240#discussion_r1795049226
> feat: improve simple asset input [LW-9231]

- src/design-system/assets-table/assets-table-token-profile.component.tsx
This PR adds a testId to the root component of TokenProfile to enable some common scenarios in E2E tests. Previously, test ids were assigned only to the child components/nodes like **ticker**, **name**, and **icon**.
> test: add testId to the root of TokenProfile [LW-11764]

- src/design-system/assets-table/assets-table-token-amount.component.tsx
- src/design-system/assets-table/assets-table.stories.tsx
- src/design-system/password-box/password-box.stories.tsx
This PR makes the `AssetTable.TokenAmount` details more configurable (previously this was hardcoded for `fiatPrice`) so that its possible to apply any text color:
> feat: make token amount details configurable [LW-11733]

- src/design-system/assets-table/assets-table-token-amount.component.tsx
- src/design-system/assets-table/assets-table.stories.tsx
This PR adds support for an optional `TokenAmount` details tooltip:
> feat: support TokenAmount details tooltip [LW-11733]

- .github/workflows/ci.yml
- .github/workflows/git-checks.yml
- .github/workflows/publish.yml
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-01
https://github.com/actions/runner-images/issues/11101
> ci: update ubuntu action runner image to 22.04

- src/design-system/profile-dropdown/profile-dropdown-wallet-card.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-card.css.ts
- src/design-system/profile-dropdown/profile-dropdown-wallet-option.component.tsx
- src/design-system/profile-dropdown/profile-dropdown-wallet-option.css.ts
- src/design-system/profile-dropdown/profile-dropdown-wallet-option.stories.tsx
This PR improves the profile dropdown wallet option markup and styles to enable correct truncation of long wallet titles that would overflow.
prerequisite for https://input-output.atlassian.net/browse/LW-12306
https://github.com/user-attachments/assets/f74e6ef1-3b30-4520-9797-bbca4ab52a0c
> fix: truncate wallet option title [LW-12306]

- src/design-tokens/sx.css.ts
This PR ensures that the popup screen (smallest) styles are applied in all smallest screen sizes (not starting at 360px which breaks layouts on sizes below).
Here is one example of the dapp connector popup which was resized to smaller than 360px and the layout is not destroyed:
> fix: apply popup styles on smaller screens [LW-12311]

- src/design-system/tooltip/tooltip-root.component.tsx
This PR fixes too strict types for `Tooltip` due to using `Pick` which loses the optional quality for picked props.
> fix: optional Tooltip props [LW-12407]

- src/design-system/asset-input/asset-input.component.tsx
- src/design-system/asset-input/asset-input.data.ts
- src/design-system/asset-input/ticker-button.component.tsx
- src/design-system/assets-table/assets-table-token-profile.component.tsx
- src/design-system/assets-table/assets-table-token-profile.css.ts
- src/design-system/assets-table/assets-table.stories.tsx
- src/design-tokens/colors.data.ts
- src/design-tokens/theme/dark-theme.css.ts
- src/design-tokens/theme/light-theme.css.ts
> make fiat optional in asset input, add badge into asset table [lw-12577]

- src/design-system/asset-input/asset-input.component.tsx
- src/design-system/asset-input/asset-input.data.ts
- src/design-system/asset-input/asset-input.fixtures.ts
- src/design-system/asset-input/ticker-button.component.tsx
- src/design-system/asset-input/ticker-button.css.ts
> feat: [lw-12215] add asset icon into asset input

- src/design-system/side-drawer/side-drawer-content-header.component.tsx
This PR removes annoying console.errors in Lace V2 and fixes one a11y aspect.
> fix: add missing DialogTitle in SideDrawer.Header
